version: '3.1'
services:
  teamspeak:
    image: ertagh/teamspeak3-server:latest-predownloaded
    restart: unless-stopped
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TIME_ZONE: Europe/London
    volumes:
      - ./save/:/teamspeak/save/