version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=Europe/London
#      - PLEX_CLAIM=
    network_mode: host
    volumes:
      - /mnt/storage/plex/config:/config
      - /mnt/storage/plex/transcode:/transcode
      - /mnt/storage/media:/data
