version: '2.4'
services:
  app:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=Europe/London
#      - PLEX_CLAIM=
    network_mode: host
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./media:/data
