version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
#      - PLEX_CLAIM=
    volumes:
      - /path/to/config:/config
      - /path/to/media:/plex/media
    restart: unless-stopped
