version: "2.4"
services:
  app:
    image: nextcloud
    container_name: nextcloud_app
    links: db
    volumes:
      - ./nextcloud:/var/www/html
    expose:
      # - 80
      # - 443
    restart: unless-stopped
  db:
    image: mariadb
    container_name: nextcloud_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: changeme
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
