version: "2.1"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./nextcloud/appdata:/config
      - ./nextcloud/data:/data
    expose:
      - 80
      - 443
    restart: unless-stopped
    depends_on:
      - mariadb
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=changeme
      - TZ=Europe/London
    volumes:
      - ./mariadb/config:/config
    expose:
      - 3306
    restart: unless-stopped
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    depends_on:
      - mariadb
      - nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=your.domain
      - SUBDOMAINS=nextcloud
      - VALIDATION=http
#      - DNSPLUGIN=cloudflare #optional
#      - PROPAGATION= #optional
#      - DUCKDNSTOKEN= #optional
#      - EMAIL= #optional
      - ONLY_SUBDOMAINS=true
#      - EXTRA_DOMAINS= #optional
#      - STAGING=false #optional
    volumes:
      - ./letsencrypt/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
