version: "2.4"
services:
  app:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./nextcloud/appdata:/config
      - ./nextcloud/data:/data
    expose:
      - 80
      - 443
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - swag
      - nextcloud
  db:
    image: linuxserver/mariadb
    container_name: nextcloud_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=changeme
      - TZ=Europe/London
    volumes:
      - ./db:/config
    restart: unless-stopped
    networks:
      - nextcloud
networks:
  nextcloud:
   name: nextcloud
  swag:
    external: true
