version: '2.4'
services:
  app:
    image: boinc/client
    container_name: boinc
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - ./boinc:/var/lib/boinc
    environment:
      - BOINC_GUI_RPC_PASSWORD=changeme
      - BOINC_CMD_LINE_OPTIONS=--allow_remote_gui_rpc