version: '2'
services:
  boinc:
    image: boinc/client
    container_name: boinc
    restart: always
    network_mode: host
    pid: host
    volumes:
      - /mnt/storage/boinc:/var/lib/boinc
    environment:
      - BOINC_GUI_RPC_PASSWORD=changeme
      - BOINC_CMD_LINE_OPTIONS=--allow_remote_gui_rpc