version: '2.4'
services:
  app:
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    expose:
      - 80
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: changeme
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - swag
      - wordpress
    depends_on:
      - db
  db:
    image: mariadb
    container_name: wordpress_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: changeme
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - wordpress

networks:
  wordpress:
    name: wordpress
  swag:
    external: true
