version: "2.4"
services:
  app:
    image: ghcr.io/linuxserver/foldingathome
    container_name: foldingathome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./foldingathome/config:/config
    ports:
      - 7396:7396
      - 36330:36330 #optional
    restart: unless-stopped