version: "2.4"
services:
  app:
    build:
      context: . 
    container_name: jenkins
    volumes:
      - ./data:/var/jenkins_home
      - ./docker-certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - 8080:8080
      - 50000:50000
    restart: unless-stopped