version: '3'
services:
  minecraft:
    image: 'openjdk:11'
    container_name: minecraft
    restart: unless-stopped
    ports:
      - 25565:25565
    volumes:
      - ./data:/srv
    stdin_open: true
    tty: true
    command: bash -c 'cd srv && java -Xmx4G -jar server.jar'
