version: "3"
services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "./path/to/server:/data"
    environment:
      TYPE: "SPIGOT"
      EULA: "TRUE"
      ENABLE_RCON: "false"
    restart: always